<?php
/**
 * Copyright 2007-2026 MEG Venture & Consulting Ltd.
 *
 * @author  MEG Venture & Consulting Ltd. <info@megventure.com>
 * @license MIT
 */
declare(strict_types=1);

namespace Megventure\Faq\Setup\Patch\Data;

use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Framework\Setup\Patch\PatchRevertableInterface;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Model\UrlPersistInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;

/**
 * Publishes the FAQ page at /faq.
 *
 * A rewrite rather than a route name, because /faq is the address customers
 * and search engines expect, and because it works without touching the web
 * server configuration.
 */
class AddFaqPageRewrite implements DataPatchInterface, PatchRevertableInterface
{
    private const REQUEST_PATH = 'faq';
    private const TARGET_PATH = 'megventure_faq/index/index';
    private const ENTITY_TYPE = 'custom';

    /**
     * @param StoreManagerInterface $storeManager
     * @param UrlPersistInterface $urlPersist
     * @param UrlRewriteFactory $urlRewriteFactory
     */
    public function __construct(
        private readonly StoreManagerInterface $storeManager,
        private readonly UrlPersistInterface $urlPersist,
        private readonly UrlRewriteFactory $urlRewriteFactory
    ) {
    }

    /**
     * Install the /faq rewrite for every store.
     *
     * @return $this
     */
    public function apply(): self
    {
        $rewrites = [];

        foreach ($this->storeManager->getStores() as $store) {
            $rewrite = $this->urlRewriteFactory->create();
            $rewrite->setEntityType(self::ENTITY_TYPE)
                ->setEntityId(0)
                ->setRequestPath(self::REQUEST_PATH)
                ->setTargetPath(self::TARGET_PATH)
                ->setRedirectType(0)
                ->setStoreId((int) $store->getId())
                ->setIsAutogenerated(0)
                ->setDescription('Product FAQ: /faq page');

            $rewrites[] = $rewrite;
        }

        if ($rewrites !== []) {
            // replace() matches on the unique (request_path, store_id) key, so
            // re-running cannot produce duplicates. A shop that already uses
            // /faq for a CMS page keeps its own: the write would collide and
            // the exception is caught below rather than breaking setup:upgrade.
            try {
                $this->urlPersist->replace($rewrites);
            } catch (\Exception $e) {
                // Left to the merchant: the module's own route still works.
                return $this;
            }
        }

        return $this;
    }

    /**
     * Remove the rewrite again on uninstall.
     *
     * @return void
     */
    public function revert(): void
    {
        foreach ($this->storeManager->getStores() as $store) {
            $this->urlPersist->deleteByData([
                'request_path' => self::REQUEST_PATH,
                'store_id' => (int) $store->getId(),
                'entity_type' => self::ENTITY_TYPE,
            ]);
        }
    }

    /**
     * @inheritDoc
     */
    public static function getDependencies(): array
    {
        return [];
    }

    /**
     * @inheritDoc
     */
    public function getAliases(): array
    {
        return [];
    }
}
