<?php
/**
 * Copyright 2007-2026 MEG Venture & Consulting Ltd.
 *
 * @author  MEG Venture & Consulting Ltd. <info@megventure.com>
 * @license MIT
 */
declare(strict_types=1);

namespace Megventure\Faq\Setup\Patch\Data;

use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Model\UrlPersistInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;

/**
 * Moves the /faq rewrite off the shared 'custom' entity type.
 *
 * 1.0.0 wrote the rewrite as (custom, 0). UrlPersist::replace() deletes every
 * row matching the entity type, entity id and store of what it writes, so this
 * module deleted the rewrites of any other module that had also used the shared
 * type — our own AI Visibility Toolkit among them, whose llms.txt stopped
 * answering. Writing under a type of our own confines replace() to our rows.
 */
class IsolateFaqPageRewrite implements DataPatchInterface
{
    private const REQUEST_PATH = 'faq';
    private const TARGET_PATH = 'megventure_faq/index/index';
    private const OLD_ENTITY_TYPE = 'custom';
    private const ENTITY_TYPE = 'megventure-faq';

    /**
     * @param StoreManagerInterface $storeManager
     * @param UrlPersistInterface $urlPersist
     * @param UrlRewriteFactory $urlRewriteFactory
     */
    public function __construct(
        private readonly StoreManagerInterface $storeManager,
        private readonly UrlPersistInterface $urlPersist,
        private readonly UrlRewriteFactory $urlRewriteFactory
    ) {
    }

    /**
     * Re-publish /faq under an entity type only this module writes.
     *
     * @return $this
     */
    public function apply(): self
    {
        $rewrites = [];

        foreach ($this->storeManager->getStores() as $store) {
            $storeId = (int) $store->getId();

            // Matched on target path, so a /faq page belonging to someone else
            // is not touched. Deleting nothing is the ordinary case.
            $this->urlPersist->deleteByData([
                'request_path' => self::REQUEST_PATH,
                'target_path' => self::TARGET_PATH,
                'store_id' => $storeId,
                'entity_type' => self::OLD_ENTITY_TYPE,
            ]);

            $rewrite = $this->urlRewriteFactory->create();
            $rewrite->setEntityType(self::ENTITY_TYPE)
                ->setEntityId(0)
                ->setRequestPath(self::REQUEST_PATH)
                ->setTargetPath(self::TARGET_PATH)
                ->setRedirectType(0)
                ->setStoreId($storeId)
                ->setIsAutogenerated(0)
                ->setDescription('Product FAQ: /faq page');

            $rewrites[] = $rewrite;
        }

        if ($rewrites !== []) {
            try {
                $this->urlPersist->replace($rewrites);
            } catch (\Exception $e) {
                // A shop that has since given /faq to a CMS page keeps it.
                return $this;
            }
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public static function getDependencies(): array
    {
        return [AddFaqPageRewrite::class];
    }

    /**
     * @inheritDoc
     */
    public function getAliases(): array
    {
        return [];
    }
}
